name: Compile

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo ::set-env name=SM_VERSION::1.10
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Compile-AS-MicroTF2
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp -E AS-MicroTF2.sp -o ../plugins/AS-MicroTF2.smx

      - name: Compile-AS-MicroTF2-MapChooser
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp -E AS-MicroTF2-MapChooser.sp -o ../plugins/AS-MicroTF2-MapChooser.smx